### ISSUE TITLE
Trying to add `tree-sitter/tree-sitter-c`

### ISSUE THREAD

**Issue by peterjmorgan** [BrianHicks/tree-grepper#205]
I've tried to follow the instructions perfectly, but I've never used `nix` before this.

I added the following stanza to `flakes.nix`:
```
  tree-sitter-c = {
      url = "github:tree-sitter/tree-sitter-c";
      flake = false;
    };
 ```
 
 and the following line to the updateVendor stanza:
 ```
 ln -s ${inputs.tree-sitter-c} vendor/tree-sitter-c
 ```
 
 then ran `direnv reload`. I don't see an operation happening that is fetching the git repo from github, so I feel like I'm missing something (perhaps obvious). 
 
 The `update-vendor` script runs, but never finds a path in `/nix/store` that has tree-sitter-c so it cannot update the symlink to the vendor directory.
 
 I'm stuck here, and hoping a nudge in the right direction might help me progress.

**Comment by BrianHicks** [comment]
Hey Peter! Sorry you're having trouble here. Good news: I tried copying/pasting your snippets myself and it looks like it works. Here's how I can tell:

- after I run `direnv reload`, I see a new entry in `flake.lock` that contains the tree-sitter-c hashes. (I pasted your snippet after line 62 in the file, but really it should be alphabetically first.)
- after `direnv reload` succeeds, running `update-vendor` creates `vendor/tree-sitter-c`

If you can see those two things as well, I think you're good to go. Otherwise, could you clarify on this by pasting the exact error message you're seeing?

> The update-vendor script runs, but never finds a path in /nix/store that has tree-sitter-c so it cannot update the symlink to the vendor directory.

**Comment by BrianHicks** [comment]
(note, however: I'm out of the office this week so I will probably be slow to respond again. It looks like you're on the right path here, though, so hopefully it's OK!)

**Comment by peterjmorgan** [comment]
@BrianHicks Thank you! For some reason, `direnv` wasn't triggering. It worked spontaneously the next time I tried, and yes, everything worked wonderfully. I got `tree-sitter-c` added and going to add `python` next :) 

I will setup a PR soon if you're interested

**Comment by BrianHicks** [comment]
yes, that'd be just fine! Until/unless we do something like #88 it'll always be fine to add more languages.
