### ISSUE TITLE
[RFC] Switch flake repos to git-submodules

### ISSUE THREAD

**Issue by Mephistophiles** [BrianHicks/tree-grepper#231]
I saw you moved tree-sitter modules from git-submodules to flakes. But this a little limits the appearance to build from a non-nix build system. Why did you drop support for git-submodules?

**Comment by BrianHicks** [comment]
A couple reasons:

- submodules have pretty terrible UX in the git command line. Maybe they're better in some client, but we can't rely on that.
- some Nix things don't support submodules. I don't remember which right now but it was a real pain.

Making symlinks or subtrees would solve this. I chose symlinks because subtrees add a lot of unrelated commits to the repo.

If this changes, I don't think we should go back to submodules, but get rid of embedded grammars altogether as in #88.

**Comment by Mephistophiles** [comment]
Thanks for the clarification!:)
